import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { scan_id } = await req.json();

    if (!scan_id) {
      return Response.json({ error: 'Missing scan_id' }, { status: 400 });
    }

    const scans = await base44.entities.SecurityScan.filter({ id: scan_id });
    if (scans.length === 0) {
      return Response.json({ error: 'Scan not found' }, { status: 404 });
    }

    const scan = scans[0];
    const vulnerabilities = scan.vulnerabilities_json || [];

    // Filter low and medium severity issues
    const remediableVulns = vulnerabilities.filter(v =>
      v.severity === 'low' || v.severity === 'medium'
    );

    if (remediableVulns.length === 0) {
      return Response.json({
        success: true,
        remediations_count: 0,
        message: 'No low/medium severity issues to remediate'
      });
    }

    const remediations = [];

    for (const vuln of remediableVulns) {
      const prompt = `You are a security expert. Generate an automated fix for this security vulnerability:

Vulnerability ID: ${vuln.id}
Type: ${vuln.type}
Severity: ${vuln.severity}
Description: ${vuln.description}
File: ${vuln.file || 'N/A'}
Line: ${vuln.line || 'N/A'}

Generate a code fix or configuration change. Return JSON:
{
  "fix_type": "code|config|dependency",
  "fix_description": "<what the fix does>",
  "code_changes": {
    "file": "<file path>",
    "original": "<original code snippet>",
    "fixed": "<fixed code snippet>"
  },
  "testing_steps": "<how to verify the fix>",
  "risk_level": "low|medium|high"
}`;

      const response = await base44.integrations.Core.InvokeLLM({
        prompt,
        response_json_schema: {
          type: 'object',
          properties: {
            fix_type: { type: 'string' },
            fix_description: { type: 'string' },
            code_changes: {
              type: 'object',
              properties: {
                file: { type: 'string' },
                original: { type: 'string' },
                fixed: { type: 'string' }
              }
            },
            testing_steps: { type: 'string' },
            risk_level: { type: 'string' }
          }
        }
      });

      remediations.push({
        vulnerability_id: vuln.id,
        severity: vuln.severity,
        fix: response
      });

      // Log the remediation
      await base44.entities.ApplicationLog.create({
        service_name: 'Security Remediation',
        severity: 'info',
        message: `Auto-generated fix for ${vuln.type} vulnerability`,
        source: 'automated_remediation',
        metadata: {
          vulnerability_id: vuln.id,
          fix_type: response.fix_type,
          file: response.code_changes?.file
        },
        timestamp: new Date().toISOString()
      });
    }

    // Create a summary PR description
    const prDescription = `## Automated Security Remediation

This PR contains ${remediations.length} automated fixes for low and medium severity security vulnerabilities.

### Fixes Applied:
${remediations.map((r, idx) => `
${idx + 1}. **${r.vulnerability_id}** (${r.severity})
   - Fix type: ${r.fix.fix_type}
   - Description: ${r.fix.fix_description}
   - File: ${r.fix.code_changes?.file || 'N/A'}
`).join('\n')}

### Testing Required:
${remediations.map(r => `- ${r.fix.testing_steps}`).join('\n')}

**⚠️ Please review and test before merging**

Generated by Enterprise Hub Security Scanner
`;

    return Response.json({
      success: true,
      remediations_count: remediations.length,
      remediations,
      pr_description: prDescription,
      message: `Generated ${remediations.length} automated fixes. Ready for PR creation.`
    });
  } catch (error) {
    console.error('Remediation error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});